TIMEOUT=0

# ── Gridz OS (installed on hard drive) ───────────────────────────────────────
:Gridz OS
    PROTOCOL=limine
    KERNEL_PATH=boot:///boot/kernel.elf
    MODULE_PATH=boot:///DOOM1.WAD
    MODULE_CMDLINE=DOOM1.WAD
