TIMEOUT=0

# ── Installer / Recovery (auto-boots when running from ISO) ──────────────────
:Gridz OS Installer
    PROTOCOL=limine
    KERNEL_PATH=boot:///boot/kernel.elf
    MODULE_PATH=boot:///DOOM1.WAD
    MODULE_CMDLINE=DOOM1.WAD
    MODULE_PATH=boot:///boot/kernel.elf
    MODULE_CMDLINE=install_kernel
    MODULE_PATH=boot:///bootblock.bin
    MODULE_CMDLINE=install_bootblock

# ── Normal OS (hidden on ISO, use only if manually selected) ─────────────────
:Gridz OS (Live)
    PROTOCOL=limine
    KERNEL_PATH=boot:///boot/kernel.elf
    MODULE_PATH=boot:///DOOM1.WAD
    MODULE_CMDLINE=DOOM1.WAD
