// Automatically generated by makemoduledefs.py.

extern const struct _mp_obj_module_t mp_module___main__;
#undef MODULE_DEF___MAIN__
#define MODULE_DEF___MAIN__ { MP_ROM_QSTR(MP_QSTR___main__), MP_ROM_PTR(&mp_module___main__) },

extern const struct _mp_obj_module_t mp_module_builtins;
#undef MODULE_DEF_BUILTINS
#define MODULE_DEF_BUILTINS { MP_ROM_QSTR(MP_QSTR_builtins), MP_ROM_PTR(&mp_module_builtins) },

extern const struct _mp_obj_module_t mp_module_files;
#undef MODULE_DEF_FILES
#define MODULE_DEF_FILES { MP_ROM_QSTR(MP_QSTR_files), MP_ROM_PTR(&mp_module_files) },

extern const struct _mp_obj_module_t mp_module_gc;
#undef MODULE_DEF_GC
#define MODULE_DEF_GC { MP_ROM_QSTR(MP_QSTR_gc), MP_ROM_PTR(&mp_module_gc) },

extern const struct _mp_obj_module_t mp_module_gridz_io;
#undef MODULE_DEF_GRIDZ_IO
#define MODULE_DEF_GRIDZ_IO { MP_ROM_QSTR(MP_QSTR_gridz_io), MP_ROM_PTR(&mp_module_gridz_io) },

extern const struct _mp_obj_module_t mp_module_random;
#undef MODULE_DEF_RANDOM
#define MODULE_DEF_RANDOM { MP_ROM_QSTR(MP_QSTR_random), MP_ROM_PTR(&mp_module_random) },


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_BUILTINS \
    MODULE_DEF_FILES \
    MODULE_DEF_GC \
    MODULE_DEF_GRIDZ_IO \
    MODULE_DEF_RANDOM \
    MODULE_DEF___MAIN__ \
// MICROPY_REGISTERED_MODULES

#define MICROPY_HAVE_REGISTERED_EXTENSIBLE_MODULES  0
